site_name: Vist's Blog
site_url: https://vist233.github.io/blog/
site_author: Vist
site_description: >-
  Welcome to my personal blog where I share my thoughts, experiences, 
  and knowledge about technology, programming, and life.

repo_name: Vist233/blog
repo_url: https://github.com/Vist233/blog

copyright: Copyright &copy; 2025 Vist

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/logo.png

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Vist233
    - icon: fontawesome/brands/email
      link: mailto:zhangyvjing@outlook.com
