site_name: My Docs
site_url: https://example.com/
site_author: Your Name
site_description: A short description of my blog.

repo_name: your-github-username/your-repo-name
repo_url: https://github.com/your-github-username/your-repo-name

copyright: Copyright &copy; 2025 Your Name

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode

plugins:
  - search
